GET http://localhost:3000/api/appointments

POST http://localhost:3000/api/appointments
Content-Type: application/json

{
    "startTime": "2024-06-01T10:30:00Z",
    "endTime": "2024-06-01T11:30:00Z",
    "customerId": 1,
    "employeeId": 4,
    "serviceId": 1
}