GET http://localhost:3000/api/appointments

GET http://localhost:3000/api/appointments/2

POST http://localhost:3000/api/appointments
Content-Type: application/json

{
    "startTime": "2026-09-16T09:00:00Z",
    "endTime": "2026-09-16T10:00:00Z",
    "customerId": 1,
    "employeeId": 2,
    "serviceId": 1
}